### ISSUE TITLE
Method CGSize..ctor not found, XamarinForms 1.0.6

### ISSUE THREAD

**Issue by MJohnsson** [jsmarcus/Xamarin.Plugins#10]
Thanks for a great plugin. I just updated my packages and now my Forms project won't run (it builds fine though). 

Exception, when loading the first tabbed view, is: _Method 'CGSize..ctor' not found._

I can add a stacktrace if that will help. Let me know.

Forms-project:
Xam.FormsPlugin.Iconize 1.0.6
Xam.Plugin.Iconize 1.0.6
Xamarin.Forms 2.2.0.31

iOS-project:
Xam.FormsPlugin.Iconize 1.0.6
Xam.Plugin.Iconize 1.0.6
Xamarin.Forms 2.2.0.31
Xam.Plugin.Iconize.FontAwesome 1.0.6

xaml example: `<iconize:IconImage Icon="fa-heart-o" IconColor="#555555" />`

**Comment by L4rS6** [comment]
This should have been fixed here: #8 
@jsmarcus is this fix already available in the nuget 1.0.6 version?

**Comment by MJohnsson** [comment]
Perhaps the merge did not make it in to the forms-plugin. Not sure, but commenting out all "iconize tags" made the app run again (although without icons obviously). At least I can keep working now :)

Crossing my fingers for an easy fix to this.

**Comment by jsmarcus** [comment]
That fix didn't make it into 1.0.6 due to a mistake on my part. It is in 1.0.7 which is dropping momentarily.

**Comment by MJohnsson** [comment]
Thanks for the prompt reply and fix.

I'm sorry to say that the new build did not help in my case. As soon as I uncomment a "iconize:IconImage" tag I get the same error. I'm not sure what version I was running initially, but it must have been a month or two old. Nothing else has been changed codewise between versions of this plugin.

All versions now indicate 1.0.7, I've cleaned and rebuilt (even restarted, heh) but as soon as the view tries to load an icon the exception is thrown.

Stacktrace attached, if at all helpful.
[stacktrace.pdf](https://github.com/jsmarcus/Xamarin.Plugins/files/261324/stacktrace.pdf)

**Comment by jsmarcus** [comment]
What version of Xamarin are you running (what channel)? Can you send some xaml or a repro project? Does the sample in the github project work for you (it does for me and uses IconImage).

**Comment by MJohnsson** [comment]
Xamarin Studio Indie
Version 5.10.3 (build 51)
Xamarin.iOS
Version: 9.6.1.9 (Xamarin Indie)
Xamarin.Mac
Version: 2.4.2.1 (Xamarin Indie)

Attaching a view that utilizes iconize. Also I'll try the sample as soon as possible!
[InspirePage.xaml.zip](https://github.com/jsmarcus/Xamarin.Plugins/files/262084/InspirePage.xaml.zip)

**Comment by L4rS6** [comment]
I've still the same problem. With your github example it's working fine, but if I use the nuget packages it's not working. **Important:** The problem only appears if I want to deploy the application to my physical iOS device, with the Simulator it's working fine.

I attached a sample, which throws the exception.

I'm using:
Xamarin.Mac
Version: 2.4.2.1 (Xamarin Business)

Xamarin.Android
Version: 6.0.3.5 (Xamarin Business)

Xamarin.iOS
Version: 9.6.1.9 (Xamarin Business)

[Iconize.zip](https://github.com/jsmarcus/Xamarin.Plugins/files/263268/Iconize.zip)

**Comment by L4rS6** [comment]
@jsmarcus could you already verify our problem?

**Comment by jsmarcus** [comment]
I haven't been able to duplicate the problem. From what I have heard from Allan Ritchie (the maker of https://github.com/aritchie/userdialogs), it is a Xamarin bug that they are working on.

**Comment by MJohnsson** [comment]
I downgraded to 1.0.4 and it seems to be working fine for now (1.0.5 did not work, either on simulator och phone).

Please update this when/if the solution gets resolved.

**Comment by TrueGeek** [comment]
I'm having this issue with the latest version of Iconize (1.0.9) and the latest version of Xamarin.Forms (2.2.0.45). Everything is updated. I used the suggestion from @MJohnsson above and downgraded to 1.0.4 and it's working great now. Awesome component, just wanted to let you know this may still be an issue.

**Comment by L4rS6** [comment]
I also reverted to version 1.0.4 an everything works well now.

**Comment by L4rS6** [comment]
Has this bug already been fixed?

**Comment by jsmarcus** [comment]
The bug was due to a Xamarin issue. I've never been able to recreate the problem but the latest build uses the latest stable release from Xamarin so I would hope it's been resolved.

**Comment by L4rS6** [comment]
It looks like Xamarin fixed the issue. I was able to deploy to my iPhone with Iconize version 1.0.10 and Xamarin.Forms 2.2.0.45. Thank you again for that great plugin!
