### ISSUE TITLE
throw ArgumentNullException on UIApplication.Main (args, null, "AppDelegate")

### ISSUE THREAD

**Issue by levuhai** [jsmarcus/Xamarin.Plugins#11]
throw ArgumentNullException on UIApplication.Main (args, null, "AppDelegate");
when adding FormsPlugin.Iconize.iOS.IconControls.Init() to AppDelegate

Plugin.Iconize.Iconize.With(new Plugin.Iconize.Fonts.MaterialModule());
global::Xamarin.Forms.Forms.Init();
**FormsPlugin.Iconize.iOS.IconControls.Init();**
LoadApplication(new App());

**Comment by L4rS6** [comment]
Add this to your Info.plist file (as mentioned here: [Setup](https://github.com/jsmarcus/Xamarin.Plugins/tree/master/Iconize) 

```
<key>UIAppFonts</key>
<array>
    <string>iconize-material.ttf</string>
</array>
```
