### ISSUE TITLE
Compatibility with portable class libraries Profile 111

### ISSUE THREAD

**Issue by eventgenius** [jsmarcus/Xamarin.Plugins#12]
Hi, do you plan to release a version for each of the Icon Fonts that is compatible with PCLs? I am trying to install the `Xam.Plugin.Iconize.FontAwesome` nuget which fails with some compatibility issue (using profile 111). All the icon fonts fail with the same message but `Xam.Plugin.Iconize` and `Xam.FormsPlugin.Iconize` installed successfully.

**Comment by jsmarcus** [comment]
The PCL doesn't hold the font so there isn't a library for it. The fonts only sit in the platform specific libraries. You don't need to reference it in the PCL project.

**Comment by Fabrik19SH** [comment]
Hi, it is obvious and logically. An hint in the documentation whould be great.
"Icon Packages should only installed on the device projects. (Visual Studio stops after first unsuccessful"

Great Package! Thanks
