### ISSUE TITLE
Could not load image named: {0}: fa-users in IconToolbarItem

### ISSUE THREAD

**Issue by thawatchai** [jsmarcus/Xamarin.Plugins#14]
I got the error `Could not load image named: {0}: fa-users` in IconToolbarItem.

The snippet is as follows:

```
	<ContentPage.ToolbarItems>
		<iconize:IconToolbarItem Icon="fa-users" />
	</ContentPage.ToolbarItems>
```

Using the icon in IconLabel works fine. So, my guess is this might be a bug in this plugin. Could you please help?

**Comment by jsmarcus** [comment]
Are you using an IconNavigationPage as your nav page to show the icons? If not they won't show. You can inherit from it but if you create a custom renderer for your inherited navigation page you will need to inherit the renderer as well.

**Comment by thawatchai** [comment]
Oh, I missed it from the sample.

However, after I've changed `NavigationPage` to `IconNavigationPage`, a **System.InvalidCastException** was thrown with the error `Specified cast is not valid`.

The app was working fine and no other thing has been changed except the class above.

Please help. Thank you very much. 😄

**Comment by tomasjuricek** [comment]
Have the same problem: System.InvalidCastException: Unable to convert instance of type 'Android.Support.V7.Widget.AppCompatTextView' to type 'Android.Support.V7.Widget.Toolbar'.

**Comment by jsmarcus** [comment]
This is due to missing info in the documentation. I will get that fixed today. When initializing the IconControls on Android the id of the toolbar and tab bar (if you are targeting either one) is needed.

```csharp
FormsPlugin.Iconize.Droid.IconControls.Init(Resource.Id.toolbar, Resource.Id.sliding_tabs);
```

**Comment by JosueMartinez** [comment]
I'm still experiencing this problem even after adding what you say @jsmarcus .  I'm also with the situation that it doesn't work when I click a toolbar item, works fine in Xamarin.iOS.  These problems are only in Android

**Comment by aquisio** [comment]
I'm also seeing this problem. Typically the first page, with 1 or more toolbar icons, is rendered correctly. If the app navigates to a nested page (pushed onto the navigation stack) it also renders its icons correctly, but when the nested page is popped, the original page is sometimes re-rendered with it's toolbar icons missing and the "Could not load image" message is logged.

This behaviour inconsistent. Forward navigation appears to always render icons correctly and sometimes backwards navigation rendering also works, but not always. I haven't seen a consistent failure pattern.

Note that it is only the rendering of the icon that is problematic. The actual toolbar buttons are always functional, even when their icons are missing.

**Comment by marlonribeiro01** [comment]
@JosueMartinez @aquisio Did you guys figure it out? I'm still facing this problem.
