### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by chkrishna2001** [jsmarcus/Xamarin.Plugins#19]
Could not install package 'Xam.Plugin.Iconize.FontAwesome 1.0.10'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am getting the above error if I try to install, could you please help me

**Comment by Kragmandu** [comment]
I am seeing the same issue with Material icons nuget package. 

Could not install package 'Xam.Plugin.Iconize.Material 1.0.10'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by hervespitz** [comment]
You don't need to install the icon packages for the Forms PCL.
Only the Android and iOS projects need them in your solution.
