### ISSUE TITLE
Still problem with IconButton

### ISSUE THREAD

**Issue by lecniers** [jsmarcus/Xamarin.Plugins#2]
<h5>I decided to report the problem again because my previous issue was closed without a right response</h5>

<h3>Answered:</h3>
<strong>I am planning on getting some documentation together but it's basically a port of Iconify. So to add an icon (or more than one) you just put it in the text. Ex: "{fa-500px} 500px"</strong>

<h2>I appreciate that but unfortunately didn't work :(</h2>  

<h3>Tested and failed</h3>
I tried that one and others combinations several times without success;

<pre>iconize:IconButton Text="{fa-500px} 500px" </pre>
above code throw this: System.Exception: Expression must end with '}'

this code doesn't fail at compile time but just print: {fa-500px} 500px and desired is to replace {fa-500px} for font icon:

<pre>iconize:IconButton Text="{}{fa-500px} 500px" </pre>
<pre>iconize:IconButton Text="{Binding Key, StringFormat='{}{{{0}}} {0}'}" </pre>
<pre>iconize:IconButton Text="{Binding Key, StringFormat='{{{0}}} {0}'}" </pre>

Tried to pass text from ViewModel fail too:

xaml: <pre>iconize:IconButton  Text="{Binding TestIcon}" </pre>
ViewModel: <pre>TestIcon = "{fa-500px} fa-500px";</pre>

**Comment by kentliaw** [comment]
Same problem here. Having issue on displaying icon for iconbutton and icontoolbaritems.

**Comment by digita1-Anal0g** [comment]
Ran into this today (for IconToolBarItem at least).  After looking through the source, a custom renderer doesn't exist for IconToolBarItem for android/iOS and so I'm guessing it's still in development (also see this [issue](https://github.com/jsmarcus/Xamarin.Plugins/issues/3#issuecomment-183335159l)).

**Comment by Korayem** [comment]
Same here. Too bad I wasted an hour getting to install this only to find that nothing works except IconImage

**Comment by po0kie** [comment]
Same here.

Is there any solution for? Or directly just supporting Text = icon and no additional text for buttons?

**Comment by Korayem** [comment]
@jsmarcus I see you closed the issue. Is it solved?

**Comment by jim-finlon** [comment]
<iconize:IconButton x:Name="MyButton" FontSize="20" Text="fa-map" TextColor="Red" WidthRequest="48" Clicked="MyEvent"/> works, but just can't find any way to combine the icon with text

**Comment by jsmarcus** [comment]
There isn't currently a way to combine an icon with text.

**Comment by jim-finlon** [comment]
Thanks for the reply, and work, still a great library!
