### ISSUE TITLE
Update docs for Xamarin.Forms

### ISSUE THREAD

**Issue by txk103** [jsmarcus/Xamarin.Plugins#21]
Using Xamarin.Forms 2.3.0.107

The documentation calls for 

> Initialize any number of modules in Application.OnCreate(). 

However, I could only get it working by making all the necessary init calls in the MainActivity.OnCreate() method.
```
protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
           
            global::Xamarin.Forms.Forms.Init(this, bundle);
            
            Plugin.Iconize.Iconize.With(new Plugin.Iconize.Fonts.FontAwesomeModule())
                                  .With(new Plugin.Iconize.Fonts.TypiconsModule());
            IconControls.Init();

            InitializeHockeyApp();
            ...
```

Is this a bug in the doco, or am I doing something wrong?

**Comment by jamesatgithub** [comment]
Yes the doc for Xamarin.Forms should be updated as above mentioned (MainApplicaiton.cs is not needed) also the font plugin should be installed on android/iOS projects, not needed on PCL project

**Comment by jsmarcus** [comment]
Documentation has been updated. Also, the repo is/has moved to https://github.com/jsmarcus/Iconize
