### ISSUE TITLE
IconToolbarItem was disappeared after switch tabs in TabbedPage

### ISSUE THREAD

**Issue by troyvnit** [jsmarcus/Xamarin.Plugins#22]
Hi guys,
Like the title of this issue, after I switch any tab, the icon was lost automatically. I used android.support.v7.widget.SearchView in toolbar.xml. Anyone face this issue?

**Comment by veeprox** [comment]
@troyvnit Did you get anywhere with this? I've run into this issue today

**Comment by troysft** [comment]
@veeprox You can fix this issue by the way changing TabbedPage to IconTabbedPage.

**Comment by troyvnit** [comment]
@veeprox Changing TabbedPage to IconTabbedPage can help you fix this issue.
