### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by rhowes** [jsmarcus/Xamarin.Plugins#23]
Hi
Everything works fine in my project except when I try and set an IconNavigationPage to MainPage of my app.cs, which gives the error System.InvalidCastException: Specified cast is not valid. The exception gets thrown in the Droid MainActivity.cs at LoadApplication (new App());

It works fine using a normal NavigationPage (without the toolbaritems obviously...).

Any suggestions greatly appreciated!
Thanks

**Comment by jsmarcus** [comment]
Can you provide some of the code you are having an issue with?

**Comment by Skulblaka** [comment]
I have the same problem and created a sample project to reproduce it: https://github.com/Skulblaka/XamIconizeIssue23

**Comment by jsmarcus** [comment]
This is due to missing info in the documentation. I will get that fixed today. When initializing the IconControls on Android the id of the toolbar and tab bar (if you are targeting either one) is needed.

```csharp
FormsPlugin.Iconize.Droid.IconControls.Init(Resource.Id.toolbar, Resource.Id.sliding_tabs);
```
