### ISSUE TITLE
Request: MasterDetailPage

### ISSUE THREAD

**Issue by Redth** [jsmarcus/Xamarin.Plugins#25]
Just getting my feet wet with this plugin, so far it's great.

I'd love to be able to easily use this for my MasterDetailPage's Master Page icon...  Is there an easy workaround currently for this?

**Comment by jsmarcus** [comment]
On Android I let the OS manage it but on iOS I've replaced the back button with one from the material design icon font. I have a BaseNavigationRenderer that inherits from IconNavigationRenderer in my iOS project with the following override.

```c#
        protected override Task<Boolean> OnPushAsync(Page page, Boolean animated)
        {
            var result = base.OnPushAsync(page, animated);

            if (NavigationPage.GetHasBackButton(page) == true)
            {
                TopViewController.NavigationItem.LeftBarButtonItem = new UIBarButtonItem(Iconize.FindIconForKey(Icons.Back).ToUIImage(25), UIBarButtonItemStyle.Plain, (sender, e) => page.SendBackButtonPressed());
                TopViewController.NavigationItem.HidesBackButton = true;
            }

            return result;
        }
```
