### ISSUE TITLE
Do I have to use FormsAppCompatActivity or can  I use FormsApplicationActivity

### ISSUE THREAD

**Issue by asj-it** [jsmarcus/Xamarin.Plugins#27]
trying to use in my Xamarin forms App,  My app uses Xamarim.Forms.Themes  so I was wanting to use `FormsApplicationActivity` but when I do I get `System.InvalidCastException: Specified cast is not valid.`.  The exception comes from ` at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.SetupToolbar () [0x00007] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:553 
`
I have not been able to upgrade to the latest version yet as some of the libraries I use are ready for standard library.

So my question is can I use FormsApplicationActivity ok with Iconize.  The issue only occurs in the Android version of the App, the IOS version seems fine.

Thanks ASh.

**Comment by veeprox** [comment]
I dont think so, i ran into the same problem a while back and the only solution was to upgrade.

**Comment by jsmarcus** [comment]
At this time only the AppCompat version of Android is supported.
