### ISSUE TITLE
IconToolbarItem with AwesomeFont

### ISSUE THREAD

**Issue by fvermeulen** [jsmarcus/Xamarin.Plugins#3]
How can I show an AwesomeFont-Icon on the ToolbarItem? 

I checked out your sample, but it doesn't show me a ToolBarItem.

`<ContentPage.ToolbarItems>
    <iconize:IconToolbarItem Icon="fa-500px" />
    <iconize:IconToolbarItem Icon="fa-500px" IconColor="Red" />
  </ContentPage.ToolbarItems>`

or with my example nothing is displayed

`var nav = new NavigationPage(
                new ContentPage {
                    Content = new IconLabel {
                        Text = "{fa-500px}"
                    },
                    ToolbarItems = {
                        new IconToolbarItem {
                            Icon = "{fa-500px}",
                            IconColor = Color.Aqua,
                        }
                    }
                }
            );
            MainPage = nav;`

Can you help me to solve my problem?

**Comment by jsmarcus** [comment]
The IconToolbarItem is not finished as it doesn't work yet for Android.

**Comment by fvermeulen** [comment]
but it also not worked on iOS

**Comment by jsmarcus** [comment]
The custom renderer needed to implement it for iOS is disabled.

**Comment by daniel-luberda** [comment]
You may want this on android: https://github.com/daniel-luberda/XamarinFormsToolbarCustomFont

**Comment by Korayem** [comment]
@jsmarcus Hey, any ETA on when will this be ready to be used in an actual production app? currently it's in alpha state to say the least
