### ISSUE TITLE
This is so awesome!

### ISSUE THREAD

**Issue by hardcodet** [jsmarcus/Xamarin.Plugins#31]
I know the issues page isn't really for this, but since private messages aren't a feature anymore...

I just wanted to tell you: You rock! I'm new to Xamarin development, and maintaining bitmaps for all those resolutions would have been a nightmare! So glad I found your project - keep up the good work!

Thanks,
Philipp

**Comment by jsmarcus** [comment]
Thank you!

p.s. - I've moved the repo to https://github.com/jsmarcus/Iconize to improve CI
