### ISSUE TITLE
Xam.Plugin.? and .net 4.5

### ISSUE THREAD

**Issue by mcaple** [jsmarcus/Xamarin.Plugins#34]
Hi just wondering if it is possible to target .net 4.5 with the icon plugins. All of them give an error like the following:

Error		Could not install package 'Xam.Plugin.Iconize.Material 1.0.10'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jsmarcus** [comment]
The icon fonts are only installed on the Android, iOS, or UWP projects, not the PCL.
