### ISSUE TITLE
IconToolbarItem not displaying

### ISSUE THREAD

**Issue by Racheldelman** [jsmarcus/Xamarin.Plugins#37]
In my project I have IconButtons working but the IconToolbarItem is not displaying:

```xaml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
		xmlns:local="clr-namespace:icon_test" x:Class="icon_test.icon_testPage"
		xmlns:iconize="clr-namespace:FormsPlugin.Iconize;assembly=FormsPlugin.Iconize">
	<ContentPage.ToolbarItems>
    	<iconize:IconToolbarItem Icon="ion-plus-circled" />
  	</ContentPage.ToolbarItems>
	<Label Text="Welcome to Xamarin Forms!" VerticalOptions="Center" HorizontalOptions="Center" />
	<iconize:IconButton FontSize="20" Text="ion-plus-circled" WidthRequest="48" />
</ContentPage>
```

This was done using the Xamarin Forms template in Xamarin Studio, nothing else was added to the project aside from the code needed to bootstrap `iconize`. Thanks!

**Comment by jaroslavrehorka** [comment]
You need to use IconNavigationPage instead of NavigationPage, please check if you do so

**Comment by Racheldelman** [comment]
@jaroslavrehorka thank you. I switched it to IconNavigationPage and it's working now.

**Comment by jon-peel** [comment]
@jaroslavrehorka  where did you change to IconNavigationPage?

**Comment by jaroslavrehorka** [comment]
When displaying a new page. Before I used NavigationPage which I replaced with IconNavigationPage. It can be seen in the example here https://github.com/jsmarcus/Xamarin.Plugins/blob/master/Iconize/Samples/Iconize.FormsSample/ModuleWrapper.cs#L65 or here https://github.com/jsmarcus/Xamarin.Plugins/blob/master/Iconize/Samples/Iconize.FormsSample/App.cs#L25

**Comment by jon-peel** [comment]
Thank you.
I was using FreshMvvm for navigation.
I created my own navigation class, copied the Fresh MVVM code from github, and changed the base class to IconNavigationPage.
This worked.
