### ISSUE TITLE
Great Plugin, but nothing works except IconImage and IconLabel. IconButton and IconToolbarItem aren't implemented.

### ISSUE THREAD

**Issue by Korayem** [jsmarcus/Xamarin.Plugins#4]
Hey, any ETA on when will this be ready to be used in an actual production app? currently it's in alpha state to say the least

**Comment by jsmarcus** [comment]
The package is full ready for production and is in several production apps (on the google and apple stores) right now. UWP is still in beta.

**Comment by Korayem** [comment]
@jsmarcus the new version implements IconButton and IconToolbarItem

**Comment by jsmarcus** [comment]
Yes. IconButton and IconToolbarItem are fully implemented for Android and iOS. Check the samples for how to use them.

**Comment by ChrisProlls** [comment]
And for UWP ?
