### ISSUE TITLE
Documentation Incomplete

### ISSUE THREAD

**Issue by kyluke** [jsmarcus/Xamarin.Plugins#45]
Good day

I'm struggling to implement this library in my Xamarin forms app but the documentation doesn't cover how to actually make use of the icons.

I've gone through the samples but it's not clear what is important and what is not. I've tried implementing as much as possible but keep hitting build errors. 

My most recent one being:
`No property, bindable property, or event found for 'Icon'`

My code is:
`<iconize:IconButton HorizontalOptions="FillAndExpand" BorderColor="#00d400" Clicked="scan_qr_code" BackgroundColor="White" BorderRadius="6" BorderWidth="1" TextColor="#00d400" Icon="fa-qrcode" x:Name="qr_code_button" FontSize="14" Grid.Row="0" Grid.Column="1" />`

**Comment by jsmarcus** [comment]
The field to use for your icon is the Text field. Also, the project has moved to https://github.com/jsmarcus/Iconize.

**Comment by kyluke** [comment]
Thanks a mil @jsmarcus!
