### ISSUE TITLE
Very confusing to start using on Android

### ISSUE THREAD

**Issue by RefuX** [jsmarcus/Xamarin.Plugins#5]
This is a documentation issue. 

Your readme does a great job on explaining how to configure it, but there is no simple "this is how to have a button with a fontawesome icon" section.

I'm having to download your sample code and debug through it to figure out how it works :(

**Comment by thawatchai** [comment]
👍  I agreed with @RefuX. The installation doc is great, but no simple how-to. I'm figuring out how to use this plugin now. Still, I couldn't find a way to use it yet. 😢

**Comment by thawatchai** [comment]
Ok, it turned out that I haven't looked hard enough. We can use this plugin by interpolating the icon name in string (like "{fa-user} User"), but I still can't make it to change the icon yet.

**Comment by L4rS6** [comment]
Just bind a string property to your button e.g.:
`<iconize:IconButton Text="{Binding MyIcon}"  />`

And the property should look like this:
```
private string _myIcon;
public string MyIcon
        {
            get
            {
                return _myIcon;
            }
            set
            {
                _myIcon = value;
                FirePropertyChanged();
            }
        }
```

**Comment by thawatchai** [comment]
Thanks, @L4rS6. I think I'll wait for the document.

(I've just started using Xamarin.Forms this week, still in the beginning of the learning curve. I hope I can contribute to the community when I'm more familiar with the tools.)

**Comment by thawatchai** [comment]
I've just installed this plugin again and it works great! Thanks for this wonderful plugin.

The trick is to follow the installation instruction carefully, then use the provided custom controls with the `Text` property as the icon name (in case of IconLabel). For example, `<iconize:IconLabel Text="fa-users" />`. Other controls might use different properties.

Don't forget to add the namespace in the beginning of the XAML file, too.
`xmlns:iconize="clr-namespace:FormsPlugin.Iconize;assembly=FormsPlugin.Iconize"`

**Comment by asj-it** [comment]
Tried to add this to my xamarin forms project, works like a charm on IOS but when I try to add the INIT command to the MainActivity I get the error:

> The name `MaterialIconControls' does not exist in the current context 

The MaterialIconControls exists in the IOS implementation but does not seem to in the Driod (I Tried adding 

`using MaterialIcons.FormsPlugin.Droid;`

manually but it still can't resolve the namespace (although it does suggest adding a using to the IOS version to fix this which must be wrong)

**Comment by jsmarcus** [comment]
@asj-it use Iconize and not MaterialIcons
