### ISSUE TITLE
How to use the Material Icons?

### ISSUE THREAD

**Issue by v3yr0n** [jsmarcus/Xamarin.Plugins#59]
Hey!

How can I use the material icons(material.io) in xamarin forms?

Thanks!

**Comment by v3yr0n** [comment]
I think that this can be added to the documentation :)
<iconize:IconImage HeightRequest="20" WidthRequest="20" Icon="md-face" IconColor="#C7C7CC"/>

**Comment by chapeti** [comment]
Yes, I agree, should be added into documentation...

**Comment by marlonribeiro01** [comment]
Alright, testing with this icon (md-face) it looks ok.
What if I want this one: local_gas_station?
How can I use it?
