### ISSUE TITLE
FormsPlugin doesn t find

### ISSUE THREAD

**Issue by ranouf** [jsmarcus/Xamarin.Plugins#64]
Hi,

I installed Xam.Plugin.Iconize.Material.
I followed the documentation.
My app uses Xamarin.Forms
When i try to add:
FormsPlugin.Iconize.Droid.IconControls.Init(Resource.Id.toolbar, Resource.Id.tabs);
AND
FormsPlugin.Iconize.iOS.IconControls.Init();
AND
xmlns:iconize="clr-namespace:FormsPlugin.Iconize;assembly=FormsPlugin.Iconize"

FormsPlugin doesnt exists.

I searched on google, but I found no response.

Can you help me please?

**Comment by akamud** [comment]
You also have to install `Xam.FormsPlugin.Iconize` in your project.

Can you try that and make sure it works? If not, can you provide a repro?

**Comment by ranouf** [comment]
I stopped using Xamarin.
Thanks for your answer, I wont be able to test.
