### ISSUE TITLE
Bug in IconTabbedPage

### ISSUE THREAD

**Issue by Li-Yanzhi** [jsmarcus/Xamarin.Plugins#68]
When I created new Xamarin Forms project in Visual Studio 2017 and added Iconize Plugin 1.0.10, then added icontoolbaritem in Xaml page and run Android project, app will throw exception and cannot start successfully.

The code is very simple, the entire project for reproducing bug at https://github.com/Li-Yanzhi/IconizeDroidTest. 

1) App.xaml.cs

            var tabbedPage = new IconTabbedPage {Title = "Iconize"};
            tabbedPage.Children.Add(new MainPage());
            MainPage = new IconNavigationPage(tabbedPage);

2. MainPage.xaml

>     ....
>     <ContentPage.ToolbarItems>
>         <iconize:IconToolbarItem Icon="fa-map-o" />
>         <iconize:IconToolbarItem  Icon="fa-bell-o" IconColor="Red" />
>         <iconize:IconToolbarItem Icon="fa-500px"  />
>     </ContentPage.ToolbarItems>

3. MainActivity.cs

       .....
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);

            Plugin.Iconize.Iconize.With(new Plugin.Iconize.Fonts.FontAwesomeModule());
            IconControls.Init(Resource.Id.toolbar, Resource.Id.sliding_tabs);

            LoadApplication(new App());
        }

In device log, I found the follow exception stack:

> Info	14867	MonoDroid	**System.NullReferenceException: Object reference not set to an instance of an object**. 
>   at FormsPlugin.Iconize.Droid.IconTabbedPageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x0002d] in ....\Xamarin.Plugins\Iconize\FormsPlugin.Iconize.Droid\IconTabbedPageRenderer.cs:44 
>   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f4] in ...1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196 
>   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in ...\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:137 
>   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager) [0x00031] in ...\Xamarin.Forms.Platform.Android\Platform.cs:325 
>   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x00008] in ...\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:67 
>   at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00022] in <27c17fe440cf491ba8255bcefade6e02>:0 
>   at (wrapper dynamic-method) System.Object:fb2216b8-fdcd-47dc-ba12-2203cb25aeb5 (intptr,intptr,intptr,intptr,intptr)

Also in Visual Studio Debug Console, we have the following output shows that the Icon file was not found, in my understanding, these Icons are in Font.ttf other than file system.

> 05-20 12:59:22.109 W/ResourceType(23730): No package identifier when getting name for resource number 0x00000000
> 05-20 12:59:22.109 W/ResourceType(23730): No package identifier when getting name for resource number 0x00000000
> [0:] Could not load image named: {0}: fa-map-o
> 05-20 12:59:22.230 W/ResourceType(23730): No package identifier when getting value for resource number 0x00000000
> 05-20 12:59:22.232 E/BitmapFactory(23730): **Unable to decode stream: java.io.FileNotFoundException: fa-map-o: open failed: ENOENT (No such file or directory)**
> [0:] Could not load image named: {0}: **fa-bell-o**
> 05-20 12:59:22.265 W/ResourceType(23730): No package identifier when getting value for resource number 0x00000000
> 05-20 12:59:22.266 E/BitmapFactory(23730): **Unable to decode stream: java.io.FileNotFoundException: fa-bell-o: open failed: ENOENT (No such file or directory)**
> [0:] Could not load image named: {0}: fa-500px
> 05-20 12:59:22.273 W/ResourceType(23730): No package identifier when getting value for resource number 0x00000000
> 05-20 12:59:22.273 E/BitmapFactory(23730): **Unable to decode stream: java.io.FileNotFoundException: fa-500px: open failed: ENOENT (No such file or directory)**
> [0:] Could not load image named: {0}: fa-map-o
> 05-20 12:59:22.307 W/ResourceType(23730): No package identifier when getting value for resource number 0x00000000
> 05-20 12:59:22.307 E/BitmapFactory(23730): **Unable to decode stream: java.io.FileNotFoundException: fa-map-o: open failed: ENOENT (No such file or directory)**
> [0:] Could not load image named: {0}: fa-bell-o
> 05-20 12:59:22.315 W/ResourceType(23730): No package identifier when getting value for resource number 0x00000000
> 05-20 12:59:22.316 E/BitmapFactory(23730): **Unable to decode stream: java.io.FileNotFoundException: fa-bell-o: open failed: ENOENT (No such file or directory)**
> [0:] Could not load image named: {0}: fa-500px
> 05-20 12:59:22.322 W/ResourceType(23730): No package identifier when getting value for resource number 0x00000000
> 05-20 12:59:22.323 E/BitmapFactory(23730): **Unable to decode stream: java.io.FileNotFoundException: fa-500px: open failed: ENOENT (No such file or directory)**

**Comment by jsmarcus** [comment]
You haven't set the icon for the tab page.

**Comment by Li-Yanzhi** [comment]
Thanks @jsmarcus , after I added Icon property for child pages of IconTabbedPage, it works.
