### ISSUE TITLE
Propouse to add some code into IconTabbedPage

### ISSUE THREAD

**Issue by SirAndriy** [jsmarcus/Xamarin.Plugins#9]
Hi, it's very exciting to use your plugins, but when I try use IconTabPage I discover that it not supported fontIcons, so I created own renderer on IconTabPage to solve this issue:

[assembly: ExportRenderer(typeof(IconTabbedPage), typeof(IconTabbedPageRenderer))]
namespace BossDesk.Droid.Controls
{
	public class IconTabbedPageRenderer : TabbedPageRenderer
	{
		private List<string> _fontIcons = new List<string>();

		protected override void OnAttachedToWindow()
		{
			SetIcon();
			base.OnAttachedToWindow();
		}

		protected override void OnElementChanged(ElementChangedEventArgs<TabbedPage> e)
		{
			var tabbetPage = e.NewElement;
			_fontIcons.Clear();
			if (tabbetPage != null || tabbetPage.Children.Any())
			{
				foreach (var page in tabbetPage.Children)
				{
					_fontIcons.Add(page.Icon.File);
					// Clear icon to solve unexisting resource
					page.Icon = null;
				}
			}

			base.OnElementChanged(e);
		}

		private void SetIcon()
		{

			var appCompatActivity = (MainActivity)Context;
			if (appCompatActivity != null)
			{
				var tabLayoutIdName = appCompatActivity.Resources
					.GetResourceName(FormsAppCompatActivity.TabLayoutResource).Replace("layout", "id");
				var tabLayoutId = appCompatActivity.Resources.GetIdentifier(tabLayoutIdName, null, null);

				var tabLayout = appCompatActivity.FindViewById<TabLayout>(tabLayoutId);

				if (tabLayout?.TabCount > 0)
				{
					for (var tabIndex = 0; tabIndex < tabLayout?.TabCount; tabIndex++)
					{
						var tab = tabLayout.GetTabAt(tabIndex);

						var icon = Plugin.Iconize.Iconize.FindIconForKey(_fontIcons[tabIndex]);
						if (icon == null)
						{
							tab.SetIcon(Android.Resource.Color.Transparent);
							continue;
						}

						var drawable = new IconDrawable(Context, icon).Color(Color.White.ToAndroid())
							.SizeDp(20);

						tab.SetIcon(drawable);
					}
				}
			}
		}
	}
}

Now it's only for Android and AppCompat, but if you interest I will try to that for iOS and simple actionBar

p.s. my xaml:

    <iconize:IconTabbedPage.Children>
        <Page Icon="fa-info-circle"></Page>
        <Page Icon="fa-paste"></Page>
        <Page Icon="fa-users"></Page>
        <Page Icon="fa-file-text"></Page>
        <Page Icon="fa-floppy-o"></Page>
        <Page Icon="fa-files-o"></Page>
    </iconize:IconTabbedPage.Children>

**Comment by SirAndriy** [comment]
p.p.s: example for iOS

[assembly:ExportRenderer (typeof(MainPage), typeof(MainPageRenderer))]
namespace Renderers.iOS
{
  public class MainPageRenderer : TabbedRenderer
  {
    public override void ViewWillAppear(bool animated)
    {
      base.ViewWillAppear(animated);

      var pages = this.ViewController.ChildViewControllers
                                     .OfType<IVisualElementRenderer>()
                                     .Select(e => e.Element as ITabPage)
                                     .ToArray();

      if (pages.Length != this.TabBar.Items.Length)
      {
        throw new Exception("Uh oh! Inconsistent number of pages and tabbar items!");
      }
    
      for (var i = 0; i < pages.Length; i++)
      {
        var tabItem = this.TabBar.Items[i];
        if (tabItem.Image == null)
        {
          tabItem.Image = ImageHelper.ImageFromFont(pages[i].Icon, UIColor.Black, new CGSize(35, 35));
          tabItem.SelectedImage = ImageHelper.ImageFromFont(pages[i].SelectedIcon, UIColor.Black, new CGSize(35, 35));
        }
      }
    }
  }
}

**Comment by jsmarcus** [comment]
I have added tabbed page renderers similar to the ones you've proposed. They are in the new release 1.0.6
