### ISSUE TITLE
Material Icons not showing

### ISSUE THREAD

**Issue by IsmaelMendonca** [jsmarcus/Xamarin.Plugins#96]
Hello Guys,

I am trying to use the Iconize in Xamarin.Forms but until now I was not successful.

I configured everything as required following the instructions in the start page and using the sample avaiable but when I try to use the IconImage setting the Icon property with a Material icon name, nothing happens. Errors are not being accused but the icon is still not appearing. Maybe I am confused about the information that I need to give in the Icon property to work as expected, the sample doesn't give me anything else about how to use the Material Icons.

If anyone could help me with an example it would be amazing.

Here is an example of how I am trying to do it.

`<iconize:IconImage Icon="airplane" IconColor="blue" HeightRequest="20" WidthRequest="20">`

**Comment by marlonribeiro01** [comment]
Try this:
`<iconize:IconImage Icon="md-airplane" IconColor="blue" HeightRequest="20" WidthRequest="20">`

**Comment by IsmaelMendonca** [comment]
@marlonribeiro01 Thank you very much! Worked perfectly! I was forgeting about the "md" prefix.
