### ISSUE TITLE
iOS displays the same icon

### ISSUE THREAD

**Issue by Jhanbury** [jsmarcus/Xamarin.Plugins#97]
I've just downloaded the FontAwesome plugin in my Prism Xamarin Forms application.
On android everything works perfectly, however, on iOS it seems that no matter what icon name I give it displays the same icon.

Is this a known issue? has anyone experienced this?

Plugin Version: 1.5.0.13-beta

**Comment by castrojr913** [comment]
@Jhanbury The same thing too.

**Comment by castrojr913** [comment]
@Jhanbury I found a workaround: Copy ttf files (e.g. iconize-fontawesome.ttf) to Resources folder on iOS Project. You can find them here: https://github.com/jsmarcus/Iconize/tree/master/src/Fonts

**Comment by Jhanbury** [comment]
still the same issue for me @castrojr913 are there any other steps you performed to fix the issue?
What was the build action on the .ttf file?

**Comment by castrojr913** [comment]
@Jhanbury. Add these font names into info.plist:

````
<key>UIAppFonts</key>
	<array>
		<string>iconize-entypoplus.ttf</string>
		<string>iconize-fontawesome.ttf</string>
		<string>iconize-ionicons.ttf</string>
		<string>iconize-material.ttf</string>
	</array>
</key>
````
Then, download .ttf files from that link and copy them the to Resources folder on your iOS project. Ok, I did this procedure with a Xamarin Forms project.

**Comment by Jhanbury** [comment]
I'm closing this as @castrojr913 solution worked for me
